### ISSUE TITLE
Diseño de objeto 3d en Blender

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-equipo-magaly#1]
[reporte de diseño 3d en blender_desarrollo de realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-equipo-magaly/files/14671765/reporte.de.diseno.3d.en.blender_desarrollo.de.realidad.aumentada.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
